version: '3.8'

#Przyk³adowy skrypt inicjalizacyjny mo¿na dodaæ do kontenera, ale wymaga to dodatkowej konfiguracji.
#Upewnij siê, ¿e masz zainstalowany Docker i Docker Compose na swoim systemie przed uruchomieniem tego pliku.
#Aby uruchomiæ kontener, u¿yj polecenia: docker-compose up -d w katalogu, w którym znajduje siê ten plik.yml.
#docker-compose up -d by odpalic w docker desktop
#by siê po³¹czyæ z baz¹ danych w sql server management studio
#server name: localhost,1433
#login: sa
#password: YourStrong@Passw0rd 
#Mo¿na to zrobiæ za pomoc¹ skryptu inicjalizacyjnego lub rêcznie w SSMS.
#Pamiêtaj, aby zmieniæ has³o na silne i bezpieczne w œrodowisku produkcyjnym.
#Ten plik docker-compose definiuje us³ugê SQL Server 2022 z trwa³ym przechowywaniem danych.
#dodaj migracje i utwórz bazê danych CompanyIntranet
#zrob to za pomoca komendt add-migration i update-database w package manager console 
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    container_name: company-intranet-db

volumes:
  sql-data: